# Generated by Django 3.2.3 on 2021-06-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20210605_1726'),
        ('products_app', '0003_auto_20210605_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='users_app.usercategory'),
        ),
    ]
